apiVersion: v1
kind: Pod
metadata:
  name: celery-flower
  labels:
    app: celery-flower
spec:
  containers:
  - name: celery-flower
    image: mher/flower:latest
    env:
    - name: ENV_VARIABLE
      value: value