apiVersion: v1
kind: Pod
metadata:
  name: celery-worker
  labels:
    app: celery-worker
spec:
  containers:
  - name: celery-worker
    image: orchest/celery-worker:v2023.04.2
    env:
    - name: ENV_VARIABLE
      value: value