apiVersion: v1
kind: Pod
metadata:
  name: celery-worker
  labels:
    app: celery-worker
spec:
  containers:
  - name: celery-worker
    image: vykintasmak/celery-worker-ntb:latest
    env:
    - name: ENV_VARIABLE
      value: value